apps/audits/urls.py
from django.urls import path

from . import views

app_name = 'audits'

urlpatterns = [
    path('', views.AuditList.as_view(), name='list'),
    path('create', views.AuditCreate.as_view(), name='create'),
    path('<uuid:pk>', views.AuditDetail.as_view(), name='detail'),
    path('<uuid:pk>/update', views.AuditUpdate.as_view(), name='update'),
    path('<uuid:pk>/delete/', views.AuditDelete.as_view(), name='delete'),
    path('<uuid:pk>/fill/', views.AuditFill.as_view(), name='fill'),
    path('<uuid:pk>/clone/', views.AuditClone.as_view(), name='clone'),

    path('answer', views.AnswerList.as_view(), name='answer-list'),
    path('answer/create', views.AnswerCreate.as_view(), name='answer-create'),
    path('answer/<uuid:pk>', views.AnswerDetail.as_view(), name='answer-detail'),
    path('answer/<uuid:pk>/update', views.AnswerUpdate.as_view(), name='answer-update'),
    path('answer/<uuid:pk>/delete/', views.AnswerDelete.as_view(), name='answer-delete'),
    path('answer/<uuid:pk>/clone/', views.AnswerClone.as_view(), name='answer-clone'),

    path('question', views.QuestionList.as_view(), name='question-list'),
    path('question/create', views.QuestionCreate.as_view(), name='question-create'),
    path('question/<uuid:pk>', views.QuestionDetail.as_view(), name='question-detail'),
    path('question/<uuid:pk>/update', views.QuestionUpdate.as_view(), name='question-update'),
    path('question/<uuid:pk>/delete/', views.QuestionDelete.as_view(), name='question-delete'),
    path('question/<uuid:pk>/clone/', views.QuestionClone.as_view(), name='question-clone'),

    path('template', views.TemplateList.as_view(), name='template-list'),
    path('template/create', views.TemplateCreate.as_view(), name='template-create'),
    path('template/<uuid:pk>', views.TemplateDetail.as_view(), name='template-detail'),
    path('template/<uuid:pk>/update', views.TemplateUpdate.as_view(), name='template-update'),
    path('template/<uuid:pk>/delete/', views.TemplateDelete.as_view(), name='template-delete'),
    path('template/<uuid:pk>/clone/', views.TemplateClone.as_view(), name='template-clone'),
]

moss_internal_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.core import views as core_views


handler404 = 'apps.core.views.handler404'
handler500 = 'apps.core.views.handler500'
handler403 = 'apps.core.views.handler403'
handler400 = 'apps.core.views.handler400'

urlpatterns = [
    path('', core_views.HomeView.as_view(), name='index'),
    path('', include('apps.accounts.urls')),
    path('representatives/', include('apps.representatives.urls')),
    path('infractions/', include('apps.infractions.urls')),
    path('audits/', include('apps.audits.urls')),
    path('superpanel/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/audits/models.py
from django.db import models
from sortedm2m.fields import SortedManyToManyField

from moss_internal_portal.mixins import UUIDPrimaryKeyMixin, CreatedModifiedMixin
from apps.representatives.models import Representative


class ChoiceAnswer(UUIDPrimaryKeyMixin, CreatedModifiedMixin):
    category = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=150)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.category} - {self.name}' if self.category else self.name


class Question(UUIDPrimaryKeyMixin, CreatedModifiedMixin):
    TYPE = (
        ('CHOICE', 'Choice'),
        ('NUMBER', 'Number'),
        ('TEXT', 'Text'),
        ('YESNO', 'Yes/No'),
    )
    category = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=150)
    type = models.CharField(max_length=50, choices=TYPE)
    answers = models.ManyToManyField(ChoiceAnswer, blank=True, verbose_name="Choice Answers")
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.category} - {self.name}' if self.category else self.name


class Template(UUIDPrimaryKeyMixin, CreatedModifiedMixin):
    category = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=150)
    questions = SortedManyToManyField(Question, blank=True)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.category} - {self.name}' if self.category else self.name


class Audit(UUIDPrimaryKeyMixin, CreatedModifiedMixin):
    representative = models.ForeignKey(Representative, on_delete=models.CASCADE, related_name='audits')
    template = models.ForeignKey(Template, on_delete=models.CASCADE, related_name='audits')
    call_date = models.DateField()
    phone = models.CharField(max_length=20)
    department = models.CharField(max_length=150, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{str(self.representative)} - {str(self.template)}"


class Response(UUIDPrimaryKeyMixin, CreatedModifiedMixin):
    audit = models.ForeignKey(Audit, on_delete=models.CASCADE, related_name='responses')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='responses')
    choice_answer = models.ForeignKey(ChoiceAnswer, on_delete=models.CASCADE, blank=True, null=True)
    text_answer = models.TextField(blank=True, null=True)
    number_answer = models.FloatField(blank=True, null=True)
    yesno_answer = models.BooleanField(blank=True, null=True)

    def __str__(self):
        return str(self.audit)


class Attachment(UUIDPrimaryKeyMixin, CreatedModifiedMixin):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)
    file_extension = models.CharField(max_length=10, blank=True, null=True)
    audit = models.ForeignKey(Audit, on_delete=models.CASCADE, related_name='attachments')
    file = models.FileField()

    def __str__(self):
        return self.name

apps/audits/views.py
from django.contrib import messages
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404, redirect
from django.forms.models import model_to_dict

from .models import *
from .forms import *


### ChoiceAnswer Viewsets ###

class AnswerList(LoginRequiredMixin, ListView):
    model = ChoiceAnswer
    login_url = '/login'
    context_object_name = 'entities'
    paginate_by = 10

    def get_queryset(self):
        keyword = self.request.GET.get('q', '')
        enabled = self.request.GET.get('enabled')

        q = Q(name__icontains=keyword)

        if enabled:
            enabled = enabled == 'true'
            q &= Q(enabled=enabled)

        return ChoiceAnswer.objects.filter(q).order_by('name')

    def get_context_data(self, **kwargs):
        context = super(AnswerList, self).get_context_data(**kwargs)
        entities = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(entities, self.paginate_by)

        try:
            entities = paginator.page(page)
        except PageNotAnInteger:
            entities = paginator.page(1)
        except EmptyPage:
            entities = paginator.page(paginator.num_pages)
        context[self.context_object_name] = entities

        return context


class AnswerDetail(LoginRequiredMixin, DetailView):
    model = ChoiceAnswer
    context_object_name = 'entity'
    login_url = '/login'

    @method_decorator(permission_required('audits.view_choiceanswer', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(AnswerDetail, self).dispatch(request)


class AnswerCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = ChoiceAnswer
    success_url = reverse_lazy('audits:answer-list')
    success_message = 'Answer created successfully.'
    login_url = '/login'
    fields = '__all__'

    @method_decorator(permission_required('audits.add_choiceanswer', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(AnswerCreate, self).dispatch(request)


class AnswerUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ChoiceAnswer
    context_object_name = 'entity'
    success_url = reverse_lazy('audits:answer-list')
    success_message = 'Answer updated successfully.'
    login_url = '/login'
    fields = '__all__'

    @method_decorator(permission_required('audits.change_choiceanswer', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(AnswerUpdate, self).dispatch(request)


class AnswerDelete(LoginRequiredMixin, DeleteView):
    model = ChoiceAnswer
    success_url = reverse_lazy('audits:answer-list')
    success_message = 'Answer deleted successfully.'
    login_url = '/login'

    @method_decorator(permission_required('audits.delete_choiceanswer', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(AnswerDelete, self).dispatch(request)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(AnswerDelete, self).delete(request, *args, **kwargs)


class AnswerClone(View):
    form_class = AnswerForm
    template_name = 'audits/choiceanswer_form.html'

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        entity = get_object_or_404(self.form_class.Meta.model, pk=pk)
        entity.id = None
        entity.name = entity.name + '_copy'
        form = self.form_class(initial=model_to_dict(entity))

        return render(request, self.template_name, locals())


### Question Viewsets ###

class QuestionList(LoginRequiredMixin, ListView):
    model = Question
    login_url = '/login'
    context_object_name = 'entities'
    paginate_by = 10

    def get_queryset(self):
        keyword = self.request.GET.get('q', '')
        enabled = self.request.GET.get('enabled')

        q = Q(name__icontains=keyword)

        if enabled:
            enabled = enabled == 'true'
            q &= Q(enabled=enabled)

        return Question.objects.filter(q).order_by('name')

    def get_context_data(self, **kwargs):
        context = super(QuestionList, self).get_context_data(**kwargs)
        entities = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(entities, self.paginate_by)

        try:
            entities = paginator.page(page)
        except PageNotAnInteger:
            entities = paginator.page(1)
        except EmptyPage:
            entities = paginator.page(paginator.num_pages)
        context[self.context_object_name] = entities

        return context


class QuestionDetail(LoginRequiredMixin, DetailView):
    model = Question
    context_object_name = 'entity'
    login_url = '/login'

    @method_decorator(permission_required('audits.view_question', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(QuestionDetail, self).dispatch(request)


class QuestionCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Question
    success_url = reverse_lazy('audits:question-list')
    success_message = 'Question created successfully.'
    login_url = '/login'
    fields = '__all__'

    def get_form(self, *args, **kwargs):
        form = super(QuestionCreate, self).get_form(*args, **kwargs)
        form.fields['answers'].queryset = ChoiceAnswer.objects.filter(enabled=True)
        return form

    @method_decorator(permission_required('audits.add_question', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(QuestionCreate, self).dispatch(request)


class QuestionUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Question
    context_object_name = 'entity'
    success_url = reverse_lazy('audits:question-list')
    success_message = 'Question updated successfully.'
    login_url = '/login'
    fields = '__all__'

    def get_form(self, *args, **kwargs):
        form = super(QuestionUpdate, self).get_form(*args, **kwargs)
        form.fields['answers'].queryset = ChoiceAnswer.objects.filter(enabled=True)
        return form

    @method_decorator(permission_required('audits.change_question', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(QuestionUpdate, self).dispatch(request)


class QuestionDelete(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = reverse_lazy('audits:question-list')
    success_message = 'Question deleted successfully.'
    login_url = '/login'

    @method_decorator(permission_required('audits.delete_question', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(QuestionDelete, self).dispatch(request)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(QuestionDelete, self).delete(request, *args, **kwargs)


class QuestionClone(View):
    form_class = QuestionForm
    template_name = 'audits/question_form.html'

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        entity = get_object_or_404(self.form_class.Meta.model, pk=pk)
        entity.id = None
        entity.name = entity.name + '_copy'
        form = self.form_class(initial=model_to_dict(entity))

        return render(request, self.template_name, locals())


### TemplateList Viewsets ###

class TemplateList(LoginRequiredMixin, ListView):
    model = Template
    login_url = '/login'
    context_object_name = 'entities'
    paginate_by = 10

    def get_queryset(self):
        keyword = self.request.GET.get('q', '')
        enabled = self.request.GET.get('enabled')

        q = Q(name__icontains=keyword)

        if enabled:
            enabled = enabled == 'true'
            q &= Q(enabled=enabled)

        return Template.objects.filter(q).order_by('name')

    def get_context_data(self, **kwargs):
        context = super(TemplateList, self).get_context_data(**kwargs)
        entities = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(entities, self.paginate_by)

        try:
            entities = paginator.page(page)
        except PageNotAnInteger:
            entities = paginator.page(1)
        except EmptyPage:
            entities = paginator.page(paginator.num_pages)
        context[self.context_object_name] = entities

        return context


class TemplateDetail(LoginRequiredMixin, DetailView):
    model = Template
    context_object_name = 'entity'
    login_url = '/login'

    @method_decorator(permission_required('audits.view_template', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(TemplateDetail, self).dispatch(request)


class TemplateCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Template
    form_class = TemplateForm
    success_url = reverse_lazy('audits:template-list')
    success_message = 'Template created successfully.'
    login_url = '/login'

    @method_decorator(permission_required('audits.add_template', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(TemplateCreate, self).dispatch(request)

    def form_valid(self, form):
        self.object = form.save()
        self.object.questions.clear()
        for question_id in self.request.POST.getlist('questions'):

moss_internal_portal/templates/audits/audit_confirm_delete.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/audits/">Audits</a></li>
  <li class="breadcrumb-item active">Delete</li>
</ol>
{% endblock %}


{% block content %}

<div class="card">
    <div class="card-header">
        <h4 class="card-title my-1">Delete Audit ({{object}})</h4>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            <a href="{% url 'audits:list' %}" class="btn btn-light btn-sm ml-1">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

moss_internal_portal/templates/audits/audit_list.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/audits/">Audits</a></li>
  <li class="breadcrumb-item active">All</li>
</ol>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-lg-8">
                        <form class="form-inline" method="GET">
                            <div class="form-group mb-2">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search...">
                            </div>
                            <button type="submit" class="btn btn-light mb-2">Search</button>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right">
                            <a type="button" href="{% url 'audits:create' %}" class="btn btn-primary mb-2 mr-2"><i class="mdi mdi-plus-circle mr-1"></i> Add New</a>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="id-check-all">
                                        <label class="custom-control-label" for="id-check-all">&nbsp;</label>
                                    </div>
                                </th>
                                <!-- <th scope="col">ID</th> -->
                                <th scope="col">Representative</th>
                                <th scope="col">Template</th>
                                <th scope="col">Call Date</th>
                                <th scope="col">Phone</th>
                                <th scope="col">Department</th>
                                <th scope="col">Notes</th>
                                <th style="width: 175px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entity in entities  %}
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input row-checkbox" id="{{entity.id}}">
                                        <label class="custom-control-label" for="{{entity.id}}">&nbsp;</label>
                                    </div>
                                </td>
                                <!-- <td><a href="{% url 'audits:detail' entity.id %}" class="text-body font-weight-bold">{{entity.id}}</a> </td> -->
                                <td>{{entity.representative}}</td>
                                <td>{{entity.template}}</td>
                                <td>{{entity.call_date}}</td>
                                <td>{{entity.phone}}</td>
                                <td>{{entity.department|default:'-'}}</td>
                                <td>{{entity.notes|truncatewords:5}}</td>
                                <td>
                                    <a href="{% url 'audits:clone' entity.id %}" class="action-icon" title="Clone"> <i class="uil uil-copy"></i></a>
                                    <a href="{% url 'audits:fill' entity.id %}" class="action-icon" title="Fill Response"> <i class="uil-file-edit-alt"></i></a>
                                    <a href="{% url 'audits:detail' entity.id %}" class="action-icon" title="View"> <i class="mdi mdi-eye"></i></a>
                                    <a href="{% url 'audits:update' entity.id %}" class="action-icon" title="Edit"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="{% url 'audits:delete' entity.id %}" class="action-icon" title="Delete"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    {% include "_pagination.html" %}
                {% endif %}
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>

{% endblock %}

moss_internal_portal/templates/audits/choiceanswer_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/audits/">Audits</a></li>
  <li class="breadcrumb-item"><a href="/audits/answer">Template Answers</a></li>
  <li class="breadcrumb-item active">{% if entity.id %}Edit{% else %}Create{% endif %}</li>
</ol>
{% endblock %}


{% block content %}

<div class="card">
    <div class="card-header">
        {% if entity.id %}
            <h4 class="card-title my-1">Update Choice Answer</h4>
        {% else %}
            <h4 class="card-title my-1">Create New Choice Answer</h4>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-7">
                <form method="post" action="{% if entity.id %}{% url 'audits:answer-update' entity.id %}{% else %}{% url 'audits:answer-create' %}{% endif %}">
                    {% csrf_token %}
                    {{form|crispy}}

                    {% if entity.id %}
                        <button type="submit" class="btn btn-success btn-sm">Update</button>
                    {% else %}
                        <button type="submit" class="btn btn-success btn-sm">Create</button>
                    {% endif %}

                    <a href="{% url 'audits:answer-list' %}" class="btn btn-light btn-sm ml-1">Cancel</a>
                </form>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

moss_internal_portal/templates/audits/template_form.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/audits/">Audits</a></li>
  <li class="breadcrumb-item"><a href="/audits/template">Templates</a></li>
  <li class="breadcrumb-item active">{% if entity.id %}Edit{% else %}Create{% endif %}</li>
</ol>
{% endblock %}

{% block content %}

<div class="card">
    <div class="card-header">
        {% if entity.id %}
            <h4 class="card-title my-1">Update Template</h4>
        {% else %}
            <h4 class="card-title my-1">Create New Template</h4>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-7">
                {{form.errors}}
                <form method="post" action="{% if entity.id %}{% url 'audits:template-update' entity.id %}{% else %}{% url 'audits:template-create' %}{% endif %}">
                    {% csrf_token %}
                    <div id="div_id_category" class="form-group">
                        <label for="id_category" class=""> Category </label>
                        {{ form.category }}
                    </div>
                    <div id="div_id_name" class="form-group">
                        <label for="id_name" class=" requiredField"> Name<span class="asteriskField">*</span> </label>
                        {{ form.name }}
                    </div>

                    <div id="div_id_questions" class="form-group">
                        <label for="" class=" requiredField">Questions <span class="font-italic small">(Choose items and order by drag & drop.)</span></label>
                        {{ form.questions }}
                    </div>

                    <div class="form-group">
                        <div id="div_id_enabled" class="custom-control custom-checkbox">
                            {{ form.enabled }}
                            <label for="id_enabled" class="custom-control-label"> Enabled </label>
                        </div>
                    </div>

                    {% if entity.id %}
                        <button type="submit" class="btn btn-success btn-sm">Update</button>
                    {% else %}
                        <button type="submit" class="btn btn-success btn-sm">Create</button>
                    {% endif %}

                    <a href="{% url 'audits:template-list' %}" class="btn btn-light btn-sm ml-1">Cancel</a>
                </form>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/vendor/dragula.min.js'%}"></script>
    <script src="{% static 'js/ui/component.dragula.js'%}"></script>
{% endblock %}

moss_internal_portal/templates/audits/template_list.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/audits/">Audits</a></li>
  <li class="breadcrumb-item"><a href="/audits/template">Templates</a></li>
  <li class="breadcrumb-item active">All</li>
</ol>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-lg-8">
                        <form class="form-inline" method="GET">
                            <div class="form-group mb-2">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search...">
                            </div>
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="status-select" class="mr-2">Enabled</label>
                                <select class="custom-select" id="status-select" name="enabled">
                                    <option value="">Choose...</option>
                                    <option value="true" {% if request.GET.enabled == "true" %}selected{% endif %}>Yes</option>
                                    <option value="false" {% if request.GET.enabled == "false" %}selected{% endif %}>No</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-light mb-2">Search</button>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right">
                            <a type="button" href="{% url 'audits:template-create' %}" class="btn btn-primary mb-2 mr-2"><i class="mdi mdi-plus-circle mr-1"></i> Add New</a>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="id-check-all">
                                        <label class="custom-control-label" for="id-check-all">&nbsp;</label>
                                    </div>
                                </th>
                                <!-- <th scope="col">ID</th> -->
                                <th scope="col">Name</th>
                                <th scope="col">Category</th>
                                <th scope="col">Enabled</th>
                                <th style="width: 150px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entity in entities  %}
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input row-checkbox" id="{{entity.id}}">
                                        <label class="custom-control-label" for="{{entity.id}}">&nbsp;</label>
                                    </div>
                                </td>
                                <!-- <td><a href="{% url 'audits:template-detail' entity.id %}" class="text-body font-weight-bold">{{entity.id}}</a> </td> -->
                                <td>{{entity.name}}</td>
                                <td>{{entity.category|default:"-"}}</td>
                                <td>{{entity.enabled|yesno|title}}</td>
                                <td>
                                    <a href="{% url 'audits:template-clone' entity.id %}" class="action-icon" title="Clone"> <i class="uil uil-copy"></i></a>
                                    <a href="{% url 'audits:template-detail' entity.id %}" class="action-icon" title="View"> <i class="mdi mdi-eye"></i></a>
                                    <a href="{% url 'audits:template-update' entity.id %}" class="action-icon" title="Edit"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="{% url 'audits:template-delete' entity.id %}" class="action-icon" title="Delete"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    {% include "_pagination.html" %}
                {% endif %}
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>

{% endblock %}