apps/infractions/urls.py
from django.urls import path

from . import views

app_name = 'infractions'

urlpatterns = [
    path('', views.InfractionList.as_view(), name='list'),
    path('create', views.InfractionCreate.as_view(), name='create'),
    path('<uuid:pk>', views.InfractionDetail.as_view(), name='detail'),
    path('<uuid:pk>/update', views.InfractionUpdate.as_view(), name='update'),
    path('<uuid:pk>/delete/', views.InfractionDelete.as_view(), name='delete'),
    path('type', views.InfractionTypeList.as_view(), name='type-list'),
    path('type/create', views.InfractionTypeCreate.as_view(), name='type-create'),
    path('type/<uuid:pk>', views.InfractionTypeDetail.as_view(), name='type-detail'),
    path('type/<uuid:pk>/update', views.InfractionTypeUpdate.as_view(), name='type-update'),
    path('type/<uuid:pk>/delete/', views.InfractionTypeDelete.as_view(), name='type-delete'),
]

apps/representatives/urls.py
from django.urls import path

from . import views

app_name = 'representatives'

urlpatterns = [
    path('', views.RepresentativeList.as_view(), name='list'),
    path('create', views.RepresentativeCreate.as_view(), name='create'),
    path('<uuid:pk>', views.RepresentativeDetail.as_view(), name='detail'),
    path('<uuid:pk>/update', views.RepresentativeUpdate.as_view(), name='update'),
    path('<uuid:pk>/delete/', views.RepresentativeDelete.as_view(), name='delete'),
]

moss_internal_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.core import views as core_views


handler404 = 'apps.core.views.handler404'
handler500 = 'apps.core.views.handler500'
handler403 = 'apps.core.views.handler403'
handler400 = 'apps.core.views.handler400'

urlpatterns = [
    path('', core_views.HomeView.as_view(), name='index'),
    path('', include('apps.accounts.urls')),
    path('representatives/', include('apps.representatives.urls')),
    path('infractions/', include('apps.infractions.urls')),
    path('audits/', include('apps.audits.urls')),
    path('superpanel/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/infractions/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from moss_internal_portal.mixins import UUIDPrimaryKeyMixin
from apps.representatives.models import Representative


class InfractionType(UUIDPrimaryKeyMixin):
    name = models.CharField(max_length=150)
    points = models.FloatField(default=0, validators=[MinValueValidator(0), MaxValueValidator(1000)])
    wfh_days_forfeit = models.IntegerField("WFH Days Forfeit", default=0, validators=[MinValueValidator(0), MaxValueValidator(365)])
    rolling_months = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(36)])
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Infraction(UUIDPrimaryKeyMixin):
    representative = models.ForeignKey(Representative, on_delete=models.CASCADE, related_name="infractions")
    date = models.DateField()
    type = models.ForeignKey(InfractionType, on_delete=models.CASCADE, related_name="infractions")
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.representative} - {self.type}'

apps/infractions/forms.py
from django import forms

from apps.representatives.models import *
from .models import *


class InfractionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(InfractionForm, self).__init__(*args, **kwargs)
        self.fields['date'].widget.attrs = { 'class': 'date', 'data-toggle': 'date-picker', 'data-single-date-picker': 'true' }
        self.fields['representative'].queryset = Representative.objects.filter(status="ACTIVE")
        self.fields['type'].queryset = InfractionType.objects.filter(enabled=True)

    class Meta:
        model = Infraction
        fields = '__all__'

apps/infractions/views.py
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

from .models import *
from .forms import *


class InfractionList(LoginRequiredMixin, ListView):
    model = Infraction
    login_url = '/login'
    context_object_name = 'entities'
    paginate_by = 10

    def get_queryset(self):
        keyword = self.request.GET.get('q', '')

        q = Q(representative__first_name__icontains=keyword) \
          | Q(representative__last_name__icontains=keyword) \
          | Q(representative__email__icontains=keyword) \
          | Q(type__name__icontains=keyword)

        return Infraction.objects.filter(q)

    def get_context_data(self, **kwargs):
        context = super(InfractionList, self).get_context_data(**kwargs)
        entities = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(entities, self.paginate_by)

        try:
            entities = paginator.page(page)
        except PageNotAnInteger:
            entities = paginator.page(1)
        except EmptyPage:
            entities = paginator.page(paginator.num_pages)
        context[self.context_object_name] = entities

        return context


class InfractionDetail(LoginRequiredMixin, DetailView):
    model = Infraction
    context_object_name = 'entity'
    login_url = '/login'

    @method_decorator(permission_required('infractions.view_infraction', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionDetail, self).dispatch(request)


class InfractionCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Infraction
    success_url = reverse_lazy('infractions:list')
    success_message = 'Infraction created successfully.'
    login_url = '/login'
    form_class = InfractionForm

    @method_decorator(permission_required('infractions.add_infraction', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionCreate, self).dispatch(request)


class InfractionUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Infraction
    context_object_name = 'entity'
    success_url = reverse_lazy('infractions:list')
    success_message = 'Infraction updated successfully.'
    login_url = '/login'
    form_class = InfractionForm

    @method_decorator(permission_required('infractions.change_infraction', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionUpdate, self).dispatch(request)


class InfractionDelete(LoginRequiredMixin, DeleteView):
    model = Infraction
    success_url = reverse_lazy('infractions:list')
    success_message = 'Infraction deleted successfully.'
    login_url = '/login'

    @method_decorator(permission_required('infractions.delete_infraction', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionDelete, self).dispatch(request)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(InfractionDelete, self).delete(request, *args, **kwargs)


# Infraction Type Views
class InfractionTypeList(LoginRequiredMixin, ListView):
    model = Infraction
    login_url = '/login'
    context_object_name = 'entities'
    paginate_by = 10

    def get_queryset(self):
        keyword = self.request.GET.get('q', '')
        enabled = self.request.GET.get('enabled', '') == "true"

        q = Q(name__icontains=keyword)

        if enabled:
            q &= Q(enabled=enabled)

        return InfractionType.objects.filter(q).order_by('name')

    def get_context_data(self, **kwargs):
        context = super(InfractionTypeList, self).get_context_data(**kwargs)
        entities = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(entities, self.paginate_by)

        try:
            entities = paginator.page(page)
        except PageNotAnInteger:
            entities = paginator.page(1)
        except EmptyPage:
            entities = paginator.page(paginator.num_pages)
        context[self.context_object_name] = entities

        return context


class InfractionTypeDetail(LoginRequiredMixin, DetailView):
    model = InfractionType
    context_object_name = 'entity'
    login_url = '/login'

    @method_decorator(permission_required('infractions.view_infractiontype', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionTypeDetail, self).dispatch(request)


class InfractionTypeCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = InfractionType
    success_url = reverse_lazy('infractions:type-list')
    success_message = 'Infraction created successfully.'
    login_url = '/login'
    fields = '__all__'

    @method_decorator(permission_required('infractions.add_infractiontype', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionTypeCreate, self).dispatch(request)


class InfractionTypeUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = InfractionType
    context_object_name = 'entity'
    success_url = reverse_lazy('infractions:type-list')
    success_message = 'Infraction updated successfully.'
    login_url = '/login'
    fields = '__all__'

    @method_decorator(permission_required('infractions.change_infractiontype', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionTypeUpdate, self).dispatch(request)


class InfractionTypeDelete(LoginRequiredMixin, DeleteView):
    model = InfractionType
    success_url = reverse_lazy('infractions:type-list')
    success_message = 'Infraction deleted successfully.'
    login_url = '/login'

    @method_decorator(permission_required('infractions.delete_infractiontype', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super(InfractionTypeDelete, self).dispatch(request)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(InfractionTypeDelete, self).delete(request, *args, **kwargs)

moss_internal_portal/templates/infractions/infraction_confirm_delete.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/infractions/">Infractions</a></li>
  <li class="breadcrumb-item active">Delete</li>
</ol>
{% endblock %}


{% block content %}

<div class="card">
    <div class="card-header">
        <h4 class="card-title my-1">Delete Infraction ({{object}})</h4>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            <a href="{% url 'infractions:list' %}" class="btn btn-light btn-sm ml-1">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

moss_internal_portal/templates/infractions/infraction_list.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/infractions/">Infractions</a></li>
  <li class="breadcrumb-item active">All</li>
</ol>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-lg-8">
                        <form class="form-inline" method="GET">
                            <div class="form-group mb-2">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search...">
                            </div>
                            <button type="submit" class="btn btn-light mb-2">Search</button>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right">
                            <a type="button" href="{% url 'infractions:create' %}" class="btn btn-primary mb-2 mr-2"><i class="mdi mdi-plus-circle mr-1"></i> Add New</a>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="id-check-all">
                                        <label class="custom-control-label" for="id-check-all">&nbsp;</label>
                                    </div>
                                </th>
                                <!-- <th scope="col">ID</th> -->
                                <th scope="col">Representative</th>
                                <th scope="col">Date</th>
                                <th scope="col">Type</th>
                                <th scope="col">Notes</th>
                                <th style="width: 125px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entity in entities  %}
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input row-checkbox" id="{{entity.id}}">
                                        <label class="custom-control-label" for="{{entity.id}}">&nbsp;</label>
                                    </div>
                                </td>
                                <!-- <td><a href="{% url 'infractions:detail' entity.id %}" class="text-body font-weight-bold">{{entity.id}}</a> </td> -->
                                <td>{{entity.representative}}</td>
                                <td>{{entity.date}}</td>
                                <td>{{entity.type}}</td>
                                <td>{{entity.notes|truncatewords:5}}</td>
                                <td>
                                    <a href="{% url 'infractions:detail' entity.id %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                    <a href="{% url 'infractions:update' entity.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="{% url 'infractions:delete' entity.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    {% include "_pagination.html" %}
                {% endif %}
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>

{% endblock %}

moss_internal_portal/templates/infractions/infraction_type_confirm_delete.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/representatives/">Representatives</a></li>
  <li class="breadcrumb-item active">Delete</li>
</ol>
{% endblock %}


{% block content %}

<div class="card">
    <div class="card-header">
        <h4 class="card-title my-1">Delete Representative ({{object.email}})</h4>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            <a href="{% url 'representatives:list' %}" class="btn btn-light btn-sm ml-1">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

moss_internal_portal/templates/infractions/infraction_type_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/representatives/">Representatives</a></li>
  <li class="breadcrumb-item active">Show</li>
</ol>
{% endblock %}


{% block content %}

<div class="card">
    <div class="card-header">
      <h4 class="card-title my-1">Representative Details ({{entity}})</h4>
    </div>
    <div class="card-body">
      <dl class="row">
        <dt class="col-sm-3 col-lg-2 mb-2">First Name</dt>
        <dd class="col-sm-9">{{ entity.first_name }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Middle Initial</dt>
        <dd class="col-sm-9">{{ entity.middle_name|default:"-" }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">last Name</dt>
        <dd class="col-sm-9">{{ entity.last_name }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Email</dt>
        <dd class="col-sm-9">{{ entity.email }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Type</dt>
        <dd class="col-sm-9">{{ entity.type|default:"-" }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Status</dt>
        <dd class="col-sm-9">{{ entity.status }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Status Date</dt>
        <dd class="col-sm-9">{{ entity.last_status_date }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Last Hire Date</dt>
        <dd class="col-sm-9">{{ entity.last_hire_date }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Division</dt>
        <dd class="col-sm-9">{{ entity.division|default:"-" }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Department</dt>
        <dd class="col-sm-9">{{ entity.department|default:"-" }}</dd>
        <dt class="col-sm-3 col-lg-2 mb-2">Work Group</dt>
        <dd class="col-sm-9">{{ entity.workgroup }}</dd>
      </dl>
      <a href="{% url 'representatives:list' %}" class="btn btn-secondary btn-sm">Back</a>
    </div>
</div>

{% endblock %}

moss_internal_portal/templates/infractions/infraction_type_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/representatives/">Representatives</a></li>
  <li class="breadcrumb-item active">{% if entity.id %}Edit{% else %}Create{% endif %}</li>
</ol>
{% endblock %}


{% block content %}

<div class="card">
    <div class="card-header">
        {% if entity.id %}
            <h4 class="card-title my-1">Update Representative</h4>
        {% else %}
            <h4 class="card-title my-1">Create New Representative</h4>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-7">
                <form method="post">
                    {% csrf_token %}
                    {{form|crispy}}

                    {% if entity.id %}
                        <button type="submit" class="btn btn-success btn-sm">Update</button>
                    {% else %}
                        <button type="submit" class="btn btn-success btn-sm">Create</button>
                    {% endif %}

                    <a href="{% url 'representatives:list' %}" class="btn btn-light btn-sm ml-1">Cancel</a>
                </form>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

moss_internal_portal/templates/infractions/infraction_type_list.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/representatives/">Representatives</a></li>
  <li class="breadcrumb-item active">All</li>
</ol>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-lg-8">
                        <form class="form-inline" method="GET">
                            <div class="form-group mb-2">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search...">
                            </div>
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="status-select" class="mr-2">Status</label>
                                <select class="custom-select" id="status-select" name="status">
                                    <option value="">Choose...</option>
                                    <option value="ACTIVE" {% if request.GET.status == "ACTIVE" %}selected{% endif %}>Active</option>
                                    <option value="TERMINATED" {% if request.GET.status == "TERMINATED" %}selected{% endif %}>Terminated</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-light mb-2">Search</button>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right">
                            <a type="button" href="{% url 'representatives:create' %}" class="btn btn-primary mb-2 mr-2"><i class="mdi mdi-plus-circle mr-1"></i> Add New</a>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                                        <label class="custom-control-label" for="customCheck1">&nbsp;</label>
                                    </div>
                                </th>
                                <!-- <th scope="col">ID</th> -->
                                <th scope="col">First Name</th>
                                <th scope="col">Last Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Type</th>
                                <th scope="col">Status Date</th>
                                <th scope="col">Status</th>
                                <th scope="col">Work Group</th>
                                <th style="width: 125px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entity in entities  %}
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck2">
                                        <label class="custom-control-label" for="customCheck2">&nbsp;</label>
                                    </div>
                                </td>
                                <!-- <td><a href="{% url 'representatives:detail' entity.id %}" class="text-body font-weight-bold">{{entity.id}}</a> </td> -->
                                <td>{{entity.first_name}}</td>
                                <td>{{entity.last_name}}</td>
                                <td>{{entity.email}}</td>
                                <td>{{entity.type|default:"-"}}</td>
                                <td>{{entity.last_status_date}}</td>
                                <td><span class="badge {% if entity.status == 'ACTIVE' %}badge-success-lighten{% else %}badge-danger-lighten{% endif %}">{{entity.status}}</span></td>
                                <td>{{entity.workgroup}}</td>
                                <td>
                                    <a href="{% url 'representatives:detail' entity.id %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                    <a href="{% url 'representatives:update' entity.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="{% url 'representatives:delete' entity.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    {% include "_pagination.html" %}
                {% endif %}
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>

{% endblock %}

moss_internal_portal/templates/infractions/infractiontype_list.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item"><a href="/infractions/">Infractions</a></li>
  <li class="breadcrumb-item"><a href="/infractions/type">Types</a></li>
  <li class="breadcrumb-item active">All</li>
</ol>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-lg-8">
                        <form class="form-inline" method="GET">
                            <div class="form-group mb-2">
                                <label for="inputPassword2" class="sr-only">Search</label>
                                <input type="search" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search...">
                            </div>
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="status-select" class="mr-2">Enabled</label>
                                <select class="custom-select" id="status-select" name="enabled">
                                    <option value="">Choose...</option>
                                    <option value="true" {% if request.GET.status == "true" %}selected{% endif %}>Yes</option>
                                    <option value="false" {% if request.GET.status == "false" %}selected{% endif %}>No</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-light mb-2">Search</button>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="text-lg-right">
                            <a type="button" href="{% url 'infractions:type-create' %}" class="btn btn-primary mb-2 mr-2"><i class="mdi mdi-plus-circle mr-1"></i> Add New</a>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered mb-0">
                        <thead class="thead-light">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="id-check-all">
                                        <label class="custom-control-label" for="id-check-all">&nbsp;</label>
                                    </div>
                                </th>
                                <!-- <th scope="col">ID</th> -->
                                <th scope="col">Name</th>
                                <th scope="col">Points</th>
                                <th scope="col">WFH Days Forfeit</th>
                                <th scope="col">Rolling Months</th>
                                <th scope="col">Enabled</th>
                                <th style="width: 125px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entity in entities  %}
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input row-checkbox" id="{{entity.id}}">
                                        <label class="custom-control-label" for="{{entity.id}}">&nbsp;</label>
                                    </div>
                                </td>
                                <!-- <td><a href="{% url 'infractions:detail' entity.id %}" class="text-body font-weight-bold">{{entity.id}}</a> </td> -->
                                <td>{{entity.name}}</td>
                                <td>{{entity.points}}</td>
                                <td>{{entity.wfh_days_forfeit}}</td>
                                <td>{{entity.rolling_months}}</td>
                                <td><span class="badge {% if entity.enabled %}badge-success-lighten{% else %}badge-danger-lighten{% endif %}">{{entity.enabled|yesno|title}}</span></td>
                                <td>
                                    <a href="{% url 'infractions:type-detail' entity.id %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                    <a href="{% url 'infractions:type-update' entity.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                    <a href="{% url 'infractions:type-delete' entity.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    {% include "_pagination.html" %}
                {% endif %}
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>

{% endblock %}